language: ruby
cache:
  bundler: true
  directories:
    - spec/dummy
bundler_args: --without="development"
rvm:
  - "1.9.3"
  - "2.1"
  - jruby-19mode

before_script:
  - sh -c '[ -r spec/dummy/config/database.yml ] || bundle exec rake test_app'
